// apps-container/src/pages/login/index.tsx
import LoginForm from "./LoginForm";

const LoginView = () => {
    return (
        <div className="container grid h-svh max-w-none items-center justify-center">
            <div className="mx-auto flex w-full flex-col justify-center space-y-2 py-8 sm:w-[480px] sm:p-8">
                <LoginForm />
            </div>
        </div>
    );
}

export default LoginView;

// tide-ui-apps/tide-manager/src/views/system/login/Login.vue
<script setup lang="ts">
import LoginForm from './components/LoginForm.vue';



</script>
<template>
    <div class="flex min-h-svh flex-col items-center justify-center bg-muted p-6 md:p-10">
        <div class="w-full max-w-sm md:max-w-5xl">
            <LoginForm />
        </div>
    </div>


</template>
