// tide-ui-apps/tide-manager/src/layout/Layout.vue
<script lang="tsx">

import { useAppStore } from "@/store/modules/app";
import { useRenderLayout } from "./useRenderLayout";

import './styles/index.scss'

const { layout } = useAppStore();


const renderLayout = () => {

    switch (layout) {

        case 'defaults':
            const { renderDefaults } = useRenderLayout()
            return renderDefaults()
        case 'classics':
            const { renderClassics } = useRenderLayout()
            return renderClassics()

        default:
            break
    }
}





export default defineComponent({
    name: 'Layout',
    setup() {
        return () => (
            <section>
                {renderLayout()}
            </section>
        )
    }
})



</script>

// apps-container/src/layout/Layout.tsx
import useAppStore from "@/store/modules/app";
import { useRenderLayout } from "./useRenderLayout";

const Layout = () => {
    const { layout } = useAppStore();
    const { renderDefaults, renderClassics } = useRenderLayout();

    const renderLayout = () => {
        switch (layout) {
            case "defaults":
                return renderDefaults();
            case "classics":
                return renderClassics();
            default:
                return renderDefaults();
        }
    };

    return (
        <section className="h-svh">
            {renderLayout()}
        </section>
    );
};

export default Layout;
